apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: GitOpsEKSDemoVPC
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    enableDnsHostNames: true
    enableDnsSupport: true
    instanceTenancy: default
    region: us-east-1
  providerConfigRef:
    name: aws-provider